language: go
sudo: required

go:
  - 1.10.x
  - stable
  - master

before_script:
  # Install gometalinter
  - gometalinter_version=2.0.11
  - gometalinter_bin=gometalinter-${gometalinter_version}-linux-amd64
  - wget https://github.com/alecthomas/gometalinter/releases/download/v${gometalinter_version}/${gometalinter_bin}.tar.gz
  - tar -zxvf ${gometalinter_bin}.tar.gz
  - export PATH=$PATH:$(pwd)/${gometalinter_bin}

  # Download test data
  - pushd cs-demos && git lfs pull -I '*' && popd

script:
  - go build

  # Lint files that changed
  - changed_files=$(git diff --name-status ${TRAVIS_COMMIT_RANGE/.../..} | cut -f2 | paste -sd '|' -)
  - linter_output=$(gometalinter ./... --vendor -s msg | grep -E $changed_files | sort)
  - if [[ "$linter_output" -ne "" ]]; then echo $linter_output && exit 1; fi

  # Get list of tests to run with race detection.
  # We don't want to run the entire demo set with it because it's large and race tests take a lot longer.
  - race_tests=$(go test -list . | grep -v "TestDemoSet\|Benchmark" | head -n -1 | awk -vORS=\| '{ print $1 }' | sed 's/|$/\n/')
  # Run race tests
  - go test -v -race -run "$race_tests" -timeout 15m

  # We run all tests again to get full coverage, technically unncecessary tho
  - go test -v -timeout 30m -coverprofile=coverage.txt -coverpkg=$(go list ./... | grep -v msg | awk -vORS=, '{ print $1 }' | sed 's/,$/\n/') ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/511da3cf50cdf951116d
    on_success: change
    on_failure: always
